---
#
# Ansible managed
#
repository:
  description: Check diskspace (or inodes) available, fail if too low.
  homepage: https://buluma.github.io/
  topics: diskspace, inodes, assert, check, ansible, molecule, playbook
